name: Post

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Importing
      run: |
        sudo python3 setup.py install
        sudo python3 -m pip install pillow
    - name: Running test
      run: |
        python3 Test/APItest.py
