name: Query

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: importing
      run: |
        sudo python3 -m pip install pillow
        sudo python3 setup.py install
    - name: Running test
      run: |
        echo plz wait
